[package]
name = "pwd-123"
version = "0.1.0"
authors = ["Jonas Berlin <xkr47@outerspace.dyndns.org>"]
edition = "2018"

[dependencies]

[[bin]]
name = "ch-1"
path = "ch-1.rs"

[[bin]]
name = "ch-2"
path = "ch-2.rs"
